# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ChatUp - AI Powered Live Chat"
client_id = "4f557f94db2cdedc6caed7ad9cea4492"
application_url = "https://chatup.dev.awesoon.tech"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://gateway.dev.awesoon.tech/v1/shopify/chatup/auth-callback"
]

[webhooks]
api_version = "2023-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://gateway.dev.awesoon.tech/v1/shopify/chatup/webhook"
  customer_data_request_url = "https://gateway.dev.awesoon.tech/v1/shopify/chatup/webhook"
  shop_deletion_url = "https://gateway.dev.awesoon.tech/v1/shopify/chatup/webhook"

[pos]
embedded = false

[build]
dev_store_url = "chatup-demo.myshopify.com"
