# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "chat-up-admin-testing"
client_id = "458cc16d11790e3d38fccbfb0c77e4f2"
application_url = "https://07c2-104-142-118-153.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://gateway.awesoon.tech/v1/shopify/chat-up-admin-testing/auth-callback",
  "https://gateway.dev.awesoon.tech/v1/shopify/chat-up-admin-testing/auth-callback",
  "https://gateway.test.awesoon.tech/v1/shopify/chat-up-admin-testing/auth-callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false

[build]
dev_store_url = "ship131290.myshopify.com"
